### ISSUE TITLE
Add WeChat Mini-program Courses

### ISSUE THREAD

**Issue by qzcool** [mikesprague/udacity-nanodegrees#37]

**Comment by mikesprague** [comment]
I am unfamiliar with these courses. If they are listed freely on the public Udacity website, please feel free to reopen this issue along with a link to the content. Otherwise, as stated in the readme, I am not an Udacity or a Google employee and only have access to the content that is published publicly and made freely available. Thanks!

**Comment by qzcool** [comment]
https://cn.udacity.com/course/wechat-mini-program-nanodegree--nd666-cn

The above is the course URL in Chinese. Thanks!
